# Generated by Django 5.1.1 on 2026-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('top_product_name', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'verbose_name_plural': 'Sales analytics',
                'ordering': ['-date'],
            },
        ),
    ]
